### ISSUE TITLE
Add method for caching next expected event to be sent (in case of program/machine failure)

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-client#3]
Some function, perhaps `to_send_later(event)` that the watcher can use to set an event which is not yet finalized but will at some point be sent. 

This event will be cached to a file (persistent storage) which will be read upon next start (if present and not empty).

The problem it solves is to prevent that in the case of machine failure, long-duration events will not be lost. This function will have to be used by watchers for them to not have the problem we are out to solve by this bugfix/feature.

Discussed with @exoji2e

**Comment by johan-bjareholt** [comment]
Isn't this issue fixed with "replace_last"?

**Comment by ErikBjare** [comment]
Yup, pretty much. Closing.
