### ISSUE TITLE
Need help understanding client.py

### ISSUE THREAD

**Issue by Otto-AA** [ActivityWatch/aw-client#36]
_Sorry if this should be asked somewhere else. If so, please make a note about that._

In ActivityWatchClient a function call is made to  `self.request_queue.start()`, yet in the RequestQueue class I don't find this function, only `RequestQueue.run()` (which seems to get triggered though). Is this just a typo, or do I miss something?

Here are the related code lines:
[self.request_queue = RequestQueue(self)](https://github.com/ActivityWatch/aw-client/blob/3702ff6ee2b3fdef5f4a56e16cbb1c06995d9f2c/aw_client/client.py#L59)
[self.request_queue.start()](https://github.com/ActivityWatch/aw-client/blob/3702ff6ee2b3fdef5f4a56e16cbb1c06995d9f2c/aw_client/client.py#L269)
[RequestQueue.run](https://github.com/ActivityWatch/aw-client/blob/3702ff6ee2b3fdef5f4a56e16cbb1c06995d9f2c/aw_client/client.py#L371)

**Comment by johan-bjareholt** [comment]
The RequestQueue is a subclass of threading.Thread, look that up in the python documentation and you'll understand.

It's essentially that you call `.start()` to start the thread which will in turn call the `.run` and finally the `.stop` functions

**Comment by ErikBjare** [comment]
Yeah, what @johan-bjareholt wrote should explain it. Closing.
